sudo: required
language: php
dist: trusty

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.example .env          # Create a new .env file
  - php artisan key:generate      # Generate application key

before_script:
  - php artisan serve &                     # Start server

script: php artisan dusk
